version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 14...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | -E bash -
      - apt install -y nodejs
      - echo Installing NPM...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - nvm use 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      # Test
      - echo Building...
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
